CREATE TABLE IF NOT EXISTS sandbox (
    id BIGINT(5) AUTO_INCREMENT PRIMARY KEY COMMENT '식별자',
    name varchar(50) NOT NULL COMMENT '이름',
    age TINYINT(2) NOT NULL COMMENT '나이',
    category VARCHAR(15) NOT NULL DEFAULT 'NORMAL' COMMENT '유형',
    deleted BIT(1) NOT NULL DEFAULT 0 COMMENT '삭제여부',
    create_date DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '생성일',
    update_date DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '최종수정일'
);
COMMENT ON TABLE sandbox is '샘플 테이블';
